### PR TITLE
Chilean National Congress support

### PR DESCRIPTION
**Pull request by robsalasco**
Hi! 

First of all, thanks for your work @RobWHickman!
I added support for Chile. If you have any question just tell me.

best, Roberto.

### CODE REVIEW

**Comment by zmeers** [comment]
More for my own curiosity than anything else, but do you have an example of what the Chilean Parliament looks like?

**Comment by robsalasco** [comment]
Hi Zoe!

Yes, check here https://en.wikipedia.org/wiki/Chamber_of_Deputies_of_Chile and https://en.wikipedia.org/wiki/Senate_of_Chile

We have a fragmented bicameral congress without majorities divided in three coalitions: Nueva Mayoria, Chile Vamos and Frente Amplio.

**Comment by RobWHickman** [comment]
Many thanks Roberto!

I noticed that the Travis build for the PR is failing to plot the US congress now. I'm not entirely sure why (I haven't had time to interrogate yet) but briefly skimming the changes to the data, I noticed that there is a missing line in the data between the Chilean Diputados and Senadores data. If you remove that (e.g. remove the line of NA values when calling election_data[180:190,]) and commit the changes does that fix things?

Also could I ask you to do two things:

1) Is it possible to provide results for both houses for 3 (any 3, but preferably the 3 most recent I think) consecutive elections. I think having at least one more data point allows people to more easily sanity check things, e.g. that colour scales remain consistent between plots. Also it means that people can recreate the vignette examples (e.g. for faceting by year) with all the different election results examples we provide

2) Could you send a link to a plot made using the data. This is more so I can quickly eyeball the colours chosen and make sure they match with those used on wikipedia*. I like the idea of allowing people to add to the data as the package is fairly compact anyway, but don't want to commit to having to check stuff like that every time people do.

Best, and thanks!

**Comment by robsalasco** [comment]
Hi Rob!

I added the 3 most recent years (sorry but the links are in spanish).

https://es.wikipedia.org/wiki/Elecciones_parlamentarias_de_Chile_de_2009
https://es.wikipedia.org/wiki/Elecciones_parlamentarias_de_Chile_de_2013
https://es.wikipedia.org/wiki/Elecciones_parlamentarias_de_Chile_de_2017

chambers


What do you think? If it's ok I'll make a new PR.

Thank you!

**Comment by robsalasco** [comment]
Hi Rob!

I added the 3 most recent years (sorry but the links are in spanish).

https://es.wikipedia.org/wiki/Elecciones_parlamentarias_de_Chile_de_2009
https://es.wikipedia.org/wiki/Elecciones_parlamentarias_de_Chile_de_2013
https://es.wikipedia.org/wiki/Elecciones_parlamentarias_de_Chile_de_2017

chambers

If it's ok I'll make a new PR.

Thank you!

**Comment by robsalasco** [comment]
Hi @RobWHickman 



I added the 3 most recent years (sorry but the links are in spanish).

https://es.wikipedia.org/wiki/Elecciones_parlamentarias_de_Chile_de_2009
https://es.wikipedia.org/wiki/Elecciones_parlamentarias_de_Chile_de_2013
https://es.wikipedia.org/wiki/Elecciones_parlamentarias_de_Chile_de_2017

chambers

If it's ok I'll create a new PR.

Thank you!

**Review by RobWHickman — APPROVED** [review]
looks good- ready to be pulled across

**Pull request merged**
