### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by zmeers**
Primarily created to update README with instructions to install from CRAN. No need to merge right away, I don't think... I think it might serve us well to have a dev branch at all times?

### CODE REVIEW

**Comment by RobWHickman** [comment]
oh yeah for sure, I'll pull and leave open.

Btw (small thing, but), did you checkout this branch from master? Trying to work out where the badges disappeared?

**Review by RobWHickman — APPROVED** [review]
all good. This is super minor- is there a way to name the chunk outputs using knitr or something? Not really a big deal but did spend a few seconds wondering why they'd all increased by one until I realised

**Comment by zmeers** [comment]
Yeah, so the badges were originally in the md file but not the Rmd file. So when I ran make again, the badges disappeared because the md file compiles from the Rmd file.

**Comment by RobWHickman** [comment]
AHH ofc- mea culpa!

**Pull request merged**
