### PR TITLE
Dev -> Master

### PR DESCRIPTION
**Pull request by zmeers**
Updates to data (fixed Germany issues, spelling error with the Australian Labor Party).
Added paper in the paper folder (Rob, can you check that your affiliation (if you want one!) is correct? Thanks). 
Feel free to make whatever edits you want, I just thought we should get the ball rolling with an update.

### CODE REVIEW

**Comment by RobWHickman** [comment]
sounds good. Btw have you read anything about how to fix conflicts with rda files? Otherwise we might have to force it I guess? idk

**Comment by zmeers** [comment]
Yeah, I think it needs to be forced. TBH, I don't really know haha... I'm a bit confused about that one myself.

**Comment by zmeers** [comment]
Ahh okay, @RobWHickman , I think I fixed the data file issue. If you can review it, it should be good to go.

**Comment by RobWHickman** [comment]
perfect (y)

**Review by RobWHickman — APPROVED** [review]

**Pull request merged**
